POS/Controllers/ItemsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using POS.Data;
using POS.Models;

namespace POS.Controllers
{
    public class ItemsController : Controller
    {
        private static  POSDbContext db;
        public ItemsController(POSDbContext _context)
        {
            db = _context;
        }

        [HttpGet]
        public IActionResult Index()
        {
           
            return View();
        }

        public IActionResult AddItem()
        {
            return View();
        }
        public IActionResult UpdateItem()
        {
            return View();
        }
        public IActionResult DetailItem()
        {
            Items objItem = new Items();
            objItem.Id = 1;
            objItem.ItemName = "Laptop";
            objItem.Serial = 1;
            objItem.ItemCode = "ITM-" + objItem.Serial.ToString();
            objItem.Price = 100;
            objItem.Qunatity = 20;
            return View(objItem);
        }
        public IActionResult AllItem()
        {
            return View();
        }
        public IActionResult DeleteItem()
        {
            return View();
        }
        [HttpGet]
        public IActionResult AddItemCategory()
        {
            ItemCategories objCat = null;

            return View(objCat);
        }
        [HttpPost]
        public IActionResult AddItemCategory(ItemCategories objCat)
        {
            try
            {
                objCat.CreatedDate = DateTime.Now;
                objCat.CreatedBy = "Admin";
                db.ItemCategories.Add(objCat);
                db.SaveChanges();
                ViewBag.SMessage = "Data Saved Successfully";
            }
            catch(Exception ex)
            {
                ViewBag.EMessage = "Some Error occurred. please try again";
            }
        
            return View();
        }
        public IActionResult AllCategories()
        {
            ViewBag.SMessage = TempData["SMessage"];
            IList<ItemCategories> oListCat = null;
            oListCat = db.ItemCategories.Where(m=> m.IsDel == false).OrderBy(m=>m.CatName).ToList();
            return View(oListCat);
        }
        public IActionResult CategoryDetail(int id)

        { 
            ItemCategories objCat = db.ItemCategories.Find(id); 
            return View(objCat);
        }
        // update / edit
        public IActionResult UpdateCategory(int id)
        {
            ViewBag.SMessage = TempData["SMessage"];
            ItemCategories objCat = db.ItemCategories.Find(id);
            return View(objCat);
        }
        [HttpPost]
        public IActionResult UpdateCategory(ItemCategories objcate)
        {
            objcate.ModifiedDate = DateTime.Now;
            objcate.ModifyBy = "System";
            db.ItemCategories.Update(objcate);
            db.SaveChanges();
            TempData["SMessage"] = "Data Updated Successfully";
            return RedirectToAction(nameof(ItemsController.UpdateCategory), new {id = objcate.Id });
        }
        // delete view
        public IActionResult DeleteCategory(int id)
        {
            ItemCategories objCat = db.ItemCategories.Find(id);
            objCat.IsDel = true;
            objCat.ModifiedDate = DateTime.Now;
            objCat.ModifyBy = "Touba";
            db.ItemCategories.Update(objCat);
            db.SaveChanges();
            TempData["SMessage"] = "Data Deleted Successfully";
            return RedirectToAction(nameof(ItemsController.AllCategories));
        }
    }
}

POS/Controllers/VendorController.cs
using Microsoft.AspNetCore.Mvc;

namespace POS.Controllers
{
    public class VendorController : Controller
    {
        public IActionResult AddVendor()
        {
            var firstName = "ABC";
            var id = 0;
            ViewBag.UserName = firstName;
            ViewBag.Id = id;
           // TempData["UserInfo"] = "Request From Add Vendor";
            return RedirectToAction("AllVendors");
        }
        public IActionResult Index()
        {
            ViewBag.UserName = "ASP.NET";
            TempData["UserName"] = "ASP.NET";
            ViewBag.Id = 1;
            return View();
        }
        public IActionResult AllVendors()
        {
           ViewBag.Request = TempData["UserInfo"];
            return View();
        }
    }
}

POS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Point of Sale System</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/POS.styles.css" asp-append-version="true" />
   <link rel="stylesheet" href="vendors/bootstrap/dist/css/bootstrap.all.css">
   @* <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">*@
    
    <link rel="stylesheet" href="vendors/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="vendors/themify-icons/css/themify-icons.css">
    <link rel="stylesheet" href="vendors/flag-icon-css/css/flag-icon.min.css">
    <link rel="stylesheet" href="vendors/selectFX/css/cs-skin-elastic.css">
    <link rel="stylesheet" href="vendors/jqvmap/dist/jqvmap.min.css">


    <link rel="stylesheet" href="assets/css/style.css">

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">POS</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vendor" asp-action="AddVendor">Add Vendor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vendor" asp-action="AllVendors">All Vendor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vendor" asp-action="Index">Index</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Dashboard">Dashboard</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Items" asp-action="AddItemCategory">Add Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Items" asp-action="AllCategories">All Categories</a>
                        </li>
                      @*  <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="UserDetail">User Detail</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Items" asp-action="DetailItem">Item Detail</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="AllUsers">All Users</a>
                        </li>*@
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - POS - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>